name: ios-tests
on:
    push:
        branches:
            - main
        paths:
            - 'apps/ios/**'
            - '.github/workflows/ios-tests.yml'
    pull_request:
        branches:
            - main
        paths:
            - 'apps/ios/**'
jobs:
    unit-tests:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build
              run: xcodebuild build-for-testing -workspace apps/ios/GuideDogs.xcworkspace -scheme Soundscape -destination 'platform=iOS Simulator,name=iPhone 13'
            - name: Test
              run: xcodebuild test-without-building -workspace apps/ios/GuideDogs.xcworkspace -scheme Soundscape -destination 'platform=iOS Simulator,name=iPhone 13'
